### ISSUE TITLE
Definition for rule unicorn/prevent-abbreviations was not found 

### ISSUE THREAD

**Issue by rpadovani** [ChocPanda/eslint-config-xo-vue#12]
First of all, amazing project :-)

So I followed the README, and did `yarn add --dev xo eslint-config-xo-vue eslint-plugin-vue`.

Now my package.json looks like this:

```
{
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.9.0",
    "@vue/cli-service": "^3.9.0",
    "eslint-config-xo-vue": "^2.0.0",
    "eslint-plugin-vue": "^5.2.3",
    "vue-template-compiler": "^2.6.10",
    "xo": "^0.24.0"
  },
  "xo": {
    "extends": "xo-vue",
    "extensions": ["js", "vue"]
  }
}
```

but every time I run `yarn run xo`, for every file it says
```
✖   1:1   Definition for rule unicorn/prevent-abbreviations was not found             unicorn/prevent-abbreviations
```

Investigating a bit, the rule `unicorn/prevent-abbreviations` has been added in `eslint-plugin-unicorn` v8, while `xo` dependes on v7 of the library. You should use only rules from v7, or explicitly depend on an higher version of the unicorn

**Comment by ChocPanda** [comment]
Hi @rpadovani , sorry for the delayed response I accidentally turned off watching this project even though I'm using it myself in a few personal projects. I'm really glad you like it.

Thanks for investigating this, I didn't know xo wasn't up to date on that dependency and so I've raised #13 which should fix the issue. I assume you fixed the issue in your repo by adding the dependency manually
