### ISSUE TITLE
Peer-dependency version incorrect

### ISSUE THREAD

**Issue by ljukas** [ChocPanda/eslint-config-xo-vue#27]
The peer dependencies says that this package wants: `"eslint-plugin-vue": ">=7.12.3"`
The latest version released is `5.2.3` according to https://github.com/vuejs/eslint-plugin-vue/releases.

This should probably be changed since this will print an error whenever this package is installed since this peer dependency cannot be met.

**Comment by ChocPanda** [comment]
Fixed by #28

**Comment by ChocPanda** [comment]
Thanks for fixing this @ljukas I have just pushed a release of 3.0.1 with your changes
